### ISSUE TITLE
Response stream initial request

### ISSUE THREAD

**Issue by DoctorJohn** [gql-dart/ferry#20]
I'm wondering whether the 'initial' request performed [within the Client.responseStream](https://github.com/gql-dart/ferry/blob/master/lib/src/client/client.dart#L56) method is required or can be made controllable.

In my use case I want to setup a response stream listener when a screen is displayed, without implicitly triggering a request. The initial request is particular annoying when its a mutation the user first has to provide arguments for.

As far as I can tell, making the initial request disableable, but enabled by default for backwards compatibility, would hurt, right?

**Comment by smkhalsa** [comment]
> In my use case I want to setup a response stream listener when a screen is displayed, without implicitly triggering a request. The initial request is particular annoying when its a mutation the user first has to provide arguments for.

The request only gets run when the stream is listened to. Are you trying to use the Query flutter widget with a mutation? That's definitely not a good idea.

The readme has an [example usage for mutations](https://github.com/gql-dart/ferry#mutations).

If you're trying to listen to a query but don't want to start listening immediately, you could use a StatefulWidget and start listening to the stream when appropriate.

**Comment by DoctorJohn** [comment]
I'm using the BLoC pattern. Dunno whether you're familiar with it, so I try to keep it simple. I have a screen which is showing the user a form. When the user submits the form I want to perform a mutation. If the mutation yields errors the form may be corrected by the user and submitted again.

Every time the form is submitted an event is dispatched to the BLoC. The BLoC then is responsible for performing the actual request. I did so by using the clients responseStream method. Making use of optimistic results, the BLoC is then listening to the response stream. However, every time the user re-submits the form, another listener starts listening to the response stream. This causes all kinds of issues.

So I either need to cancel subscriptions after receving the optimistic result and possibly a network response or just subscribe once per screen (or more precicely per BLoC). I figured subscribing once I cleaner. So when a new screen is navigated to, the screens BLoC subscribes to the mutations response stream once. When the user submits the form I just add a request to the clients query controller. Responses are then received by said subscription.

So far so good. The only issue left is the initial request sent when calling the clients responseStream method. It inevitable fails in my scenario, because I do not provide the necessary build arguments when calling responseStream.

Hope this makes sense, lemme know whether you smell some missusage of ferry. I'm just trying to use it properly with the BLoC pattern.

**Comment by smkhalsa** [comment]
@DoctorJohn can you provide a code sample? I'm still not completely sure what you're trying to accomplish and where the issue is.

**Comment by smkhalsa** [comment]
If you don't want identical mutations to show up in the same responseStream, you can provide a unique queryId

**Comment by DoctorJohn** [comment]
@smkhalsa Are you familiar with the BLoC pattern? This would drastically reduce the example code I would need to provide.

At its core this issue is about whether it would make ferry more flexible if one could start listening to a response stream without implicitly triggering an initial request. Using said pattern sending requests and receiving responses asnychronously are two different concerns I'd like to separate.

**Comment by DoctorJohn** [comment]
> If you don't want identical mutations to show up in the same responseStream, you can provide a unique queryId

I actually want all mutations to show up in the same response stream. _A single listener_ is then responsible for turning these responses into new states for the screen.

Currently I cant just subscribe the one listener I need to the stream and later perform the mutation as often as I like, because subscribing to the stream does send an initial request I dont want to send in that moment.

So I'm forced to subscribe to the response stream when I actually want to perform the mutation for the first time. However, the second time I perform the mutation I do not want to subscribe to the response stream again. So I would need to check in my "performMutation" method whether I'm already subscribed or not. But as I said: being subscribed to receive responses and sending requests are two different concerns I idealy would not want to live in the same "performMutation" method.

If you guys have the feeling that's just me being finicky, feel free to let me know. I can just go with my first approche or customized the ferry Client to my needs by extending it.

**Comment by smkhalsa** [comment]
Ok, I think I agree with your premise that we should separate the ability to listen to a response stream from the actual execution of the query.

A simple optional "executeOnListen" parameter (which defaults to true) on responseStream should do the trick. See #21 and let me know if this solves the issue for you.

**Comment by DoctorJohn** [comment]
Thanks @smkhalsa, #21 solves the issue for me.
